package classification;
public enum Cluster {
	BEER, BREAD, CHEESE, COCTAIL_ALCOHOL, COCTAIL_NON_ALCOHOL, COFFIE, DESSERT, EGGS, FISH, FIZZY, KASHA, MEAT, MILK, PANCAKES, PASTA, PELMENI, PIZZA, SALAD, SANDWICH, SAUCE, SAUSAGE, SMOKE, SOUP, SOUSHI, STARTER, STRONG_ALCOHOL, TEA, VEGET, WINE;
}
